[package]
name = "local-cache"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
tokio.workspace = true
sqlx.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
uuid.workspace = true
tempfile = "3"